# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\26692\Desktop\ChatRoom_Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 300)
        self.label_FeedBack = QtWidgets.QLabel(Form)
        self.label_FeedBack.setGeometry(QtCore.QRect(70, 210, 271, 21))
        self.label_FeedBack.setText("")
        self.label_FeedBack.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FeedBack.setObjectName("label_FeedBack")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 70, 271, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_UserID2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_UserID2.setObjectName("label_UserID2")
        self.horizontalLayout_2.addWidget(self.label_UserID2)
        self.lineEdit_UserNickName = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_UserNickName.setObjectName("lineEdit_UserNickName")
        self.horizontalLayout_2.addWidget(self.lineEdit_UserNickName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_UserID = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_UserID.setObjectName("label_UserID")
        self.horizontalLayout_6.addWidget(self.label_UserID)
        self.lineEdit_UserID = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_UserID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_UserID.setObjectName("lineEdit_UserID")
        self.horizontalLayout_6.addWidget(self.lineEdit_UserID)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Password = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_Password.setObjectName("label_Password")
        self.horizontalLayout_4.addWidget(self.label_Password)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.horizontalLayout_4.addWidget(self.lineEdit_Password)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_Title = QtWidgets.QLabel(Form)
        self.label_Title.setGeometry(QtCore.QRect(90, 30, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.pushButton_Register = QtWidgets.QPushButton(Form)
        self.pushButton_Register.setGeometry(QtCore.QRect(160, 240, 75, 23))
        self.pushButton_Register.setObjectName("pushButton_Register")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "小小聊天室 -注册"))
        self.label_UserID2.setText(_translate("Form", " 昵称"))
        self.label_UserID.setText(_translate("Form", " 账号"))
        self.label_Password.setText(_translate("Form", " 密码"))
        self.label_Title.setText(_translate("Form", "User Register"))
        self.pushButton_Register.setText(_translate("Form", "注册"))
