# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\26692\Desktop\樱绮纪行2021[↓]\课程\网络编程\实验2-UDP\ChatRoom\UDPChatRoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 492)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_Screen = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_Screen.setObjectName("textBrowser_Screen")
        self.verticalLayout.addWidget(self.textBrowser_Screen)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_PriChat = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_PriChat.setObjectName("checkBox_PriChat")
        self.horizontalLayout_4.addWidget(self.checkBox_PriChat)
        self.lineEdit_PriChat = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_PriChat.setObjectName("lineEdit_PriChat")
        self.horizontalLayout_4.addWidget(self.lineEdit_PriChat)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_UserInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_UserInput.setObjectName("lineEdit_UserInput")
        self.horizontalLayout.addWidget(self.lineEdit_UserInput)
        self.pushButton_SendMessage = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_SendMessage.setObjectName("pushButton_SendMessage")
        self.horizontalLayout.addWidget(self.pushButton_SendMessage)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_PriChat.setText(_translate("Form", "私聊"))
        self.lineEdit_PriChat.setPlaceholderText(_translate("Form", "输入您想要私聊对象的昵称，可以用\';\'分割"))
        self.pushButton_SendMessage.setText(_translate("Form", "发送消息(Enter)"))
